# Create instances to go in the cluster, in the security group above
# to improve immutability, all inputs are variables that can be defined elsewhere
- hosts: localhost
  connection: local
  gather_facts: True

- name: Create VPC
  tasks:
    - ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        cidr_block: 10.0.0.0/8
        name: "{{ varVPCName }}"
        state: present
        tags:
          testenvironment: mesos-server
        register: VPC_information
