---
# This playbook deploys the entire Mesos cluster infrastructure.
# RUN: ansible-playbook --ask-sudo-pass -i hosts site.yml

#part 2 - Install Mesos cluster
#builds mesos cluster
include_task: BuildEnvironment.yml

#Part 2a - Build bootstrap node

#deploy Mesos servers
- name: deploy and configure the mesos masters
  hosts: mesos_masters
  sudo: True

  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }

- name: deploy and configure the mesos slaves
  hosts: mesos_slaves
  sudo: True

  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
